name: .NET Core CI
run-name: ${{ github.actor }} pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.201

    - name: Install dependencies
      run: dotnet restore /testing_pipeline/BlogApp

    - name: Build
      run: dotnet build /testing_pipeline/BlogApp --configuration Release --no-restore

    - name: Test
      run: dotnet test /testing_pipeline/BlogApp --no-restore --verbosity normal
