name: ASP.NET Core CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BlogApp
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Run tests and coverage
        run: dotnet test --collect:"XPlat Code Coverage"
    - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./TestResults/*/coverage.cobertura.xml
          flags: unittests