name: .Net 6 CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BlogApp
    name: CI Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          dotnet-quality: 'ga'

      - name: Restore Dependencies
        run: dotnet restore 

      - name: Build
        run: dotnet build  --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory /home/runner/work/testing_pipeline/testing_pipeline/BlogApp/TestResults

      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.19
        with:
          reports: /home/runner/work/testing_pipeline/testing_pipeline/BlogApp/TestResults
          targetdir: /home/runner/work/testing_pipeline/testing_pipeline/coveragereport
          sourcedirs: /home/runner/work/testing_pipeline/testing_pipeline/BlogApp