name: ASP.NET Core PR CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and test
      run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: Calculate code coverage
      uses: danielpalme/ReportGenerator@v4
      with:
        reports: **/coverage.opencover.xml
        targetdir: coverage
        reporttypes: HtmlInline_AzurePipelines

    - name: Upload code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage
