name: ASP.NET Core CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./BlogApp
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and test
      run: dotnet test --logger "trx;LogFileName=testresults.xml" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3